### ISSUE TITLE
Passing default role only sets default profile

### ISSUE THREAD

**Issue by louahola** [commercehub-oss/kerb-sts#16]
When passing in a default role to assume, only the [default] block in the credentials file gets overwritten. This should overwrite both the default and the named profile blocks instead of just one or the other.

**Comment by Krylon360** [comment]
+1.
We just had a use-case come about that describes this exact issue.
When specifying a role (profile) with -r ROLE_NAME it makes that the [default] profile; but doesn't create a profile entry with that name. As @louahola said; it should do both; create a [default] entry AND a named profile entry. Obviously the data would be the same; just a different profile.

Interesting enough; if you dont specify a role; it doesn't create a [default] profile entry; but it does create an entry for each Role that has the SAML Assertions within the claim.

**Comment by louahola** [comment]
Fixed in #20
