### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by ndmikkelsen** [commercehub-oss/kerb-sts#30]
(generic) ➜  kubetest git:(master) kerb-sts
09/27/2018 11:48:01 AM INFO: --------------------------------
09/27/2018 11:48:01 AM INFO:        generating tokens
09/27/2018 11:48:01 AM INFO: --------------------------------
09/27/2018 11:48:01 AM INFO: region: us-east-1
09/27/2018 11:48:01 AM INFO: url: <SSO LANDING PAGE>
09/27/2018 11:48:01 AM INFO: credentials file: <LOCAL CRED FILE>
09/27/2018 11:48:01 AM INFO: auth type: kerberos
09/27/2018 11:48:01 AM INFO: role: <ROLE>
09/27/2018 11:48:02 AM INFO: role: <ROLE>
09/27/2018 11:48:02 AM INFO: role: <ROLE>
09/27/2018 11:48:02 AM INFO: role: <ROLE>
09/27/2018 11:48:03 AM INFO: role: <ROLE>
09/27/2018 11:48:03 AM ERROR: 403 Forbidden
09/27/2018 11:48:03 AM ERROR: b'<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>AccessDenied</Code>\n    <Message>Access denied</Message>\n  </Error>\n  <RequestId>1afe5d9e-c275-11e8-8bd2-ad73bbf6a5c5</RequestId>\n</ErrorResponse>\n'
09/27/2018 11:48:03 AM ERROR: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>Access denied</Message>
  </Error>
  <RequestId>1afe5d9e-c275-11e8-8bd2-ad73bbf6a5c5</RequestId>
</ErrorResponse>

Fails the entire process, should continue and write successful role assumptions to credentials file as intended regardless of single failed assertion.

**Comment by nbrowz** [comment]
@ndmikkelsen Thanks for the report. Which version are you running?

**Comment by ndmikkelsen** [comment]
kerb-sts==0.1.3
