### ISSUE TITLE
Configurable token lifetime request

### ISSUE THREAD

**Issue by ngtrimble** [commercehub-oss/kerb-sts#38]
Would it be possible to get a feature to make the token lifetime be configurable.

Example:

kerb-sts -t EXPIRE_SECONDS
kerb-sts --time EXPIRE_SECONDS

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
